apiVersion: batch/v1
kind: Job
metadata:
  name: pre-deploy
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: main
        args:
        - /bin/sh
        - -c
        - "sleep 5 && exit 1"
        image: ghcr.io/stefanprodan/podinfo:${IMAGE_TAG}
