apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: deploy
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/bcarrier92/post-build-kustomize-dependency.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: deploy
spec:
  dependsOn:
    - name: pre-deploy
  interval: 60m
  path: deploy
  postBuild:
    substitute:
      IMAGE_TAG: "6.6.0"
  prune: true
  sourceRef:
    kind: GitRepository
    name: deploy
  wait: true
