apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pre-deploy
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/bcarrier92/post-build-kustomize-dependency.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pre-deploy
spec:
  force: true
  interval: 60m
  path: pre-deploy
  postBuild:
    substitute:
      IMAGE_TAG: "6.6.0"
  prune: true
  sourceRef:
    kind: GitRepository
    name: pre-deploy
  wait: true
